### PR TITLE
Animation support

### PR DESCRIPTION
**Pull request by tptee**
See the README diff for how the animation API works!

This PR depended on the new constraint removal support in our [fork](https://github.com/FormidableLabs/autolayout.js) of Autolayout.js.

/cc @boygirl @eastridge @kenwheeler @divmain et al

### CODE REVIEW

**Comment by kenwheeler** [comment]
This looks awesome. On local, when running builder run dev, it _sometimes_ does the intial layout, but resizing the window isn't keeping the positions synced. This is on a fresh pull.
screen shot 2016-06-06 at 8 33 38 am

**Comment by tptee** [comment]
Eww. I'll poke at it tonight!

**Comment by tptee** [comment]
Repro'd it here. What the hell is going on there? I'll try to track down the regression

**Comment by tptee** [comment]
I've confirmed that this craziness only happens against React 15. But...why??

**Comment by tptee** [comment]
This breaks React 15 rendering:

``` html
<script>
  // Sanity-check the component loaded...
  setTimeout(function () {
    var content = document.querySelector("#content");
    content.innerHTML = content.innerHTML ||
      "If you can see this, something is broken (or JS is not enabled)!";
  }, 500);
</script>
```

It's in the demo html files of many of our OSS projects. We should probably check that this doesn't happen elsewhere. @boygirl @kenwheeler @coopy

**Comment by tptee** [comment]
Going to merge, post-review comments appreciated!

**Pull request merged**
